package entidade;
// Generated 18/09/2017 19:03:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cliente generated by hbm2java
 */
@Entity
@Table(name="cliente"
    ,schema="public"
)
public class Cliente  implements java.io.Serializable {


     private int id;
     private Cidade cidade;
     private String razaoSocial;
     private String cpfCnpj;
     private char tipoCadastro;
     private String clientecol;
     private String endereco;
     private String telefone;
     private char situacao;
     private Set tarefas = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(int id, Cidade cidade, String razaoSocial, char tipoCadastro, char situacao) {
        this.id = id;
        this.cidade = cidade;
        this.razaoSocial = razaoSocial;
        this.tipoCadastro = tipoCadastro;
        this.situacao = situacao;
    }
    public Cliente(int id, Cidade cidade, String razaoSocial, String cpfCnpj, char tipoCadastro, String clientecol, String endereco, String telefone, char situacao, Set tarefas) {
       this.id = id;
       this.cidade = cidade;
       this.razaoSocial = razaoSocial;
       this.cpfCnpj = cpfCnpj;
       this.tipoCadastro = tipoCadastro;
       this.clientecol = clientecol;
       this.endereco = endereco;
       this.telefone = telefone;
       this.situacao = situacao;
       this.tarefas = tarefas;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_cidade", nullable=false)
    public Cidade getCidade() {
        return this.cidade;
    }
    
    public void setCidade(Cidade cidade) {
        this.cidade = cidade;
    }

    
    @Column(name="razao_social", nullable=false, length=150)
    public String getRazaoSocial() {
        return this.razaoSocial;
    }
    
    public void setRazaoSocial(String razaoSocial) {
        this.razaoSocial = razaoSocial;
    }

    
    @Column(name="cpf_cnpj", length=18)
    public String getCpfCnpj() {
        return this.cpfCnpj;
    }
    
    public void setCpfCnpj(String cpfCnpj) {
        this.cpfCnpj = cpfCnpj;
    }

    
    @Column(name="tipo_cadastro", nullable=false, length=1)
    public char getTipoCadastro() {
        return this.tipoCadastro;
    }
    
    public void setTipoCadastro(char tipoCadastro) {
        this.tipoCadastro = tipoCadastro;
    }

    
    @Column(name="clientecol", length=45)
    public String getClientecol() {
        return this.clientecol;
    }
    
    public void setClientecol(String clientecol) {
        this.clientecol = clientecol;
    }

    
    @Column(name="endereco", length=150)
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }

    
    @Column(name="telefone", length=15)
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

    
    @Column(name="situacao", nullable=false, length=1)
    public char getSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(char situacao) {
        this.situacao = situacao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cliente")
    public Set getTarefas() {
        return this.tarefas;
    }
    
    public void setTarefas(Set tarefas) {
        this.tarefas = tarefas;
    }




}


