package entidade;
// Generated 24/08/2017 21:27:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int id;
     private Cidade cidade;
     private String razaoSocial;
     private String cpfCnpj;
     private char tipoCadastro;
     private String clientecol;
     private String endereco;
     private String telefone;
     private char situacao;
     private Set tarefas = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(int id, Cidade cidade, String razaoSocial, char tipoCadastro, char situacao) {
        this.id = id;
        this.cidade = cidade;
        this.razaoSocial = razaoSocial;
        this.tipoCadastro = tipoCadastro;
        this.situacao = situacao;
    }
    public Cliente(int id, Cidade cidade, String razaoSocial, String cpfCnpj, char tipoCadastro, String clientecol, String endereco, String telefone, char situacao, Set tarefas) {
       this.id = id;
       this.cidade = cidade;
       this.razaoSocial = razaoSocial;
       this.cpfCnpj = cpfCnpj;
       this.tipoCadastro = tipoCadastro;
       this.clientecol = clientecol;
       this.endereco = endereco;
       this.telefone = telefone;
       this.situacao = situacao;
       this.tarefas = tarefas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Cidade getCidade() {
        return this.cidade;
    }
    
    public void setCidade(Cidade cidade) {
        this.cidade = cidade;
    }
    public String getRazaoSocial() {
        return this.razaoSocial;
    }
    
    public void setRazaoSocial(String razaoSocial) {
        this.razaoSocial = razaoSocial;
    }
    public String getCpfCnpj() {
        return this.cpfCnpj;
    }
    
    public void setCpfCnpj(String cpfCnpj) {
        this.cpfCnpj = cpfCnpj;
    }
    public char getTipoCadastro() {
        return this.tipoCadastro;
    }
    
    public void setTipoCadastro(char tipoCadastro) {
        this.tipoCadastro = tipoCadastro;
    }
    public String getClientecol() {
        return this.clientecol;
    }
    
    public void setClientecol(String clientecol) {
        this.clientecol = clientecol;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public char getSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(char situacao) {
        this.situacao = situacao;
    }
    public Set getTarefas() {
        return this.tarefas;
    }
    
    public void setTarefas(Set tarefas) {
        this.tarefas = tarefas;
    }




}


