package entidade;
// Generated 18/09/2017 19:03:04 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MovimentoTarefa generated by hbm2java
 */
@Entity
@Table(name="movimento_tarefa"
    ,schema="public"
)
public class MovimentoTarefa  implements java.io.Serializable {


     private int id;
     private Tarefa tarefa;
     private String descricao;
     private Date datahoraMovimento;
     private char situacao;
     private String anexo;
     private Usuario usuario;

    public MovimentoTarefa() {
    }

	
    public MovimentoTarefa(int id, Tarefa tarefa, String descricao, Date datahoraMovimento, char situacao) {
        this.id = id;
        this.tarefa = tarefa;
        this.descricao = descricao;
        this.datahoraMovimento = datahoraMovimento;
        this.situacao = situacao;
    }
    public MovimentoTarefa(int id, Tarefa tarefa, String descricao, Date datahoraMovimento, char situacao, String anexo) {
       this.id = id;
       this.tarefa = tarefa;
       this.descricao = descricao;
       this.datahoraMovimento = datahoraMovimento;
       this.situacao = situacao;
       this.anexo = anexo;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_tarefa", nullable=false)
    public Tarefa getTarefa() {
        return this.tarefa;
    }
    
    public void setTarefa(Tarefa tarefa) {
        this.tarefa = tarefa;
    }
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_usuario", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="descricao", nullable=false)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="datahora_movimento", nullable=false, length=29)
    public Date getDatahoraMovimento() {
        return this.datahoraMovimento;
    }
    
    public void setDatahoraMovimento(Date datahoraMovimento) {
        this.datahoraMovimento = datahoraMovimento;
    }

    
    @Column(name="situacao", nullable=false, length=1)
    public char getSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(char situacao) {
        this.situacao = situacao;
    }

    
    @Column(name="anexo", length=45)
    public String getAnexo() {
        return this.anexo;
    }
    
    public void setAnexo(String anexo) {
        this.anexo = anexo;
    }




}


