package entidade;
// Generated 24/08/2017 21:27:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Prioridade generated by hbm2java
 */
public class Prioridade  implements java.io.Serializable {


     private int id;
     private String descricao;
     private char situacao;
     private Set tarefas = new HashSet(0);

    public Prioridade() {
    }

	
    public Prioridade(int id, String descricao, char situacao) {
        this.id = id;
        this.descricao = descricao;
        this.situacao = situacao;
    }
    public Prioridade(int id, String descricao, char situacao, Set tarefas) {
       this.id = id;
       this.descricao = descricao;
       this.situacao = situacao;
       this.tarefas = tarefas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public char getSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(char situacao) {
        this.situacao = situacao;
    }
    public Set getTarefas() {
        return this.tarefas;
    }
    
    public void setTarefas(Set tarefas) {
        this.tarefas = tarefas;
    }




}


