package entidade;
// Generated 18/09/2017 19:03:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Projeto generated by hbm2java
 */
@Entity
@Table(name="projeto"
    ,schema="public"
)
public class Projeto  implements java.io.Serializable {


     private int id;
     private String descricao;
     private char situacao;
     private Set modulos = new HashSet(0);
     private Set versaos = new HashSet(0);
     private Set tarefas = new HashSet(0);

    public Projeto() {
    }

	
    public Projeto(int id, String descricao, char situacao) {
        this.id = id;
        this.descricao = descricao;
        this.situacao = situacao;
    }
    public Projeto(int id, String descricao, char situacao, Set modulos, Set versaos, Set tarefas) {
       this.id = id;
       this.descricao = descricao;
       this.situacao = situacao;
       this.modulos = modulos;
       this.versaos = versaos;
       this.tarefas = tarefas;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="descricao", nullable=false, length=60)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    
    @Column(name="situacao", nullable=false, length=1)
    public char getSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(char situacao) {
        this.situacao = situacao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="projeto")
    public Set getModulos() {
        return this.modulos;
    }
    
    public void setModulos(Set modulos) {
        this.modulos = modulos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="projeto")
    public Set getVersaos() {
        return this.versaos;
    }
    
    public void setVersaos(Set versaos) {
        this.versaos = versaos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="projeto")
    public Set getTarefas() {
        return this.tarefas;
    }
    
    public void setTarefas(Set tarefas) {
        this.tarefas = tarefas;
    }




}


