package entidade;
// Generated 24/08/2017 21:27:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Projeto generated by hbm2java
 */
public class Projeto  implements java.io.Serializable {


     private int id;
     private String descricao;
     private char situacao;
     private Set modulos = new HashSet(0);
     private Set versaos = new HashSet(0);
     private Set tarefas = new HashSet(0);

    public Projeto() {
    }

	
    public Projeto(int id, String descricao, char situacao) {
        this.id = id;
        this.descricao = descricao;
        this.situacao = situacao;
    }
    public Projeto(int id, String descricao, char situacao, Set modulos, Set versaos, Set tarefas) {
       this.id = id;
       this.descricao = descricao;
       this.situacao = situacao;
       this.modulos = modulos;
       this.versaos = versaos;
       this.tarefas = tarefas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public char getSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(char situacao) {
        this.situacao = situacao;
    }
    public Set getModulos() {
        return this.modulos;
    }
    
    public void setModulos(Set modulos) {
        this.modulos = modulos;
    }
    public Set getVersaos() {
        return this.versaos;
    }
    
    public void setVersaos(Set versaos) {
        this.versaos = versaos;
    }
    public Set getTarefas() {
        return this.tarefas;
    }
    
    public void setTarefas(Set tarefas) {
        this.tarefas = tarefas;
    }




}


