package entidade;
// Generated 18/09/2017 19:03:04 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TarefaUsuario generated by hbm2java
 */
@Entity
@Table(name="tarefa_usuario"
    ,schema="public"
)
public class TarefaUsuario  implements java.io.Serializable {


     private int id;
     private Tarefa tarefa;
     private Usuario usuario;

    public TarefaUsuario() {
    }

    public TarefaUsuario(int id, Tarefa tarefa, Usuario usuario) {
       this.id = id;
       this.tarefa = tarefa;
       this.usuario = usuario;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_tarefa", nullable=false)
    public Tarefa getTarefa() {
        return this.tarefa;
    }
    
    public void setTarefa(Tarefa tarefa) {
        this.tarefa = tarefa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_usuario", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


