package entidade;
// Generated 24/08/2017 21:27:39 by Hibernate Tools 4.3.1



/**
 * TarefaUsuario generated by hbm2java
 */
public class TarefaUsuario  implements java.io.Serializable {


     private int id;
     private Tarefa tarefa;
     private Usuario usuario;

    public TarefaUsuario() {
    }

    public TarefaUsuario(int id, Tarefa tarefa, Usuario usuario) {
       this.id = id;
       this.tarefa = tarefa;
       this.usuario = usuario;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Tarefa getTarefa() {
        return this.tarefa;
    }
    
    public void setTarefa(Tarefa tarefa) {
        this.tarefa = tarefa;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


