package entidade;
// Generated 18/09/2017 19:03:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Versao generated by hbm2java
 */
@Entity
@Table(name="versao"
    ,schema="public"
)
public class Versao  implements java.io.Serializable {


     private int id;
     private Projeto projeto;
     private String descricao;
     private char situacao;
     private Set tarefasForIdVersaoCorrecao = new HashSet(0);
     private Set tarefasForIdVersaoBug = new HashSet(0);

    public Versao() {
    }

	
    public Versao(int id, Projeto projeto, String descricao, char situacao) {
        this.id = id;
        this.projeto = projeto;
        this.descricao = descricao;
        this.situacao = situacao;
    }
    public Versao(int id, Projeto projeto, String descricao, char situacao, Set tarefasForIdVersaoCorrecao, Set tarefasForIdVersaoBug) {
       this.id = id;
       this.projeto = projeto;
       this.descricao = descricao;
       this.situacao = situacao;
       this.tarefasForIdVersaoCorrecao = tarefasForIdVersaoCorrecao;
       this.tarefasForIdVersaoBug = tarefasForIdVersaoBug;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_projeto", nullable=false)
    public Projeto getProjeto() {
        return this.projeto;
    }
    
    public void setProjeto(Projeto projeto) {
        this.projeto = projeto;
    }

    
    @Column(name="descricao", nullable=false, length=45)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    
    @Column(name="situacao", nullable=false, length=1)
    public char getSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(char situacao) {
        this.situacao = situacao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="versaoByIdVersaoCorrecao")
    public Set getTarefasForIdVersaoCorrecao() {
        return this.tarefasForIdVersaoCorrecao;
    }
    
    public void setTarefasForIdVersaoCorrecao(Set tarefasForIdVersaoCorrecao) {
        this.tarefasForIdVersaoCorrecao = tarefasForIdVersaoCorrecao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="versaoByIdVersaoBug")
    public Set getTarefasForIdVersaoBug() {
        return this.tarefasForIdVersaoBug;
    }
    
    public void setTarefasForIdVersaoBug(Set tarefasForIdVersaoBug) {
        this.tarefasForIdVersaoBug = tarefasForIdVersaoBug;
    }




}


